name: eqtl2gwas
channels:
  - defaults
  - bioconda
dependencies:
  - anaconda::libopenblas
  - bioconda::bcftools
  - bioconda::samtools
  - bioconda::tabix
  - pip
  - pip:
    - -r requirements.txt
